server:
  port: 8761

spring:
  application:
    name: discovery
  datasource:
    password: postgres
    url: jdbc:postgresql:${dockerdb}:5432/JMP
    username: postgres
    driver: org.postgresql.Drive
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
